"""Minimal ABIs for the mintable mock USDC and the ParametricEscrow."""

ERC20_ABI = [
    {"name": "mint", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "to", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": []},
    {"name": "transfer", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "to", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": [{"type": "bool"}]},
    {"name": "approve", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": [{"type": "bool"}]},
    {"name": "allowance", "type": "function", "stateMutability": "view",
     "inputs": [{"name": "owner", "type": "address"}, {"name": "spender", "type": "address"}],
     "outputs": [{"type": "uint256"}]},
    {"name": "balanceOf", "type": "function", "stateMutability": "view",
     "inputs": [{"name": "account", "type": "address"}], "outputs": [{"type": "uint256"}]},
    {"name": "decimals", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "uint8"}]},
]

ESCROW_ABI = [
    {"name": "takePolicy", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "insured", "type": "address"}, {"name": "premium", "type": "uint256"},
                {"name": "trigger", "type": "uint256"}, {"name": "payout", "type": "uint256"}],
     "outputs": [{"name": "id", "type": "uint256"}]},
    {"name": "settle", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "id", "type": "uint256"}, {"name": "indexValue", "type": "uint256"}],
     "outputs": []},
    {"name": "info", "type": "function", "stateMutability": "view",
     "inputs": [{"name": "id", "type": "uint256"}],
     "outputs": [{"name": "insured", "type": "address"}, {"name": "premium", "type": "uint256"},
                 {"name": "trigger", "type": "uint256"}, {"name": "payout", "type": "uint256"},
                 {"name": "open", "type": "bool"}, {"name": "paid", "type": "bool"}]},
    {"name": "freeLiquidity", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "uint256"}]},
    {"name": "reserved", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "uint256"}]},
    {"name": "lastIndex", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "uint256"}]},
    {"name": "policyCount", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "uint256"}]},
    {"name": "operator", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "address"}]},
    {"name": "assetToken", "type": "function", "stateMutability": "view",
     "inputs": [], "outputs": [{"type": "address"}]},
]
